presubmits:
- name: nf-deploy-controller-presubmit-test
  branches:
  - ^main$
  always_run: true
  decorate: true
  spec:
    containers:
    - image: golang:1.18
      command:
      - make
      args:
      - -f
      - Makefile
      - test
