presubmits:
  - name: nf-deploy-controller-presubmit-test
    decorate: true
    always_run: true
    spec:
      containers:
      - image: golang:1.18
        command:
        - make
        args:
        - -f
        - Makefile
        - test
