# Copyright 2022-2023 The Nephio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: UpfType
metadata:
  name: UpfTypeTest
spec:
  name: UpfTypeTest
  capacityProfile: UpfCapacityProfileTest
  N3InterfaceProfile:
  - profileName: profile301
    id: 301
  - profileName: profile302
    id: 302
  - profileName: profile303
    id: 303
  - profileName: profile304
    id: 304
  - profileName: profile305
    id: 305
  - profileName: profile306
    id: 306
  - profileName: profile307
    id: 307
  - profileName: profile308
    id: 308
  - profileName: profile309
    id: 309
  - profileName: profile310
    id: 310
  N4InterfaceProfile:
  - profileName: profile41
    id: 41
  - profileName: profile42
    id: 42
  - profileName: profile43
    id: 43
  - profileName: profile44
    id: 44
  - profileName: profile45
    id: 45
  - profileName: profile46
    id: 46
  - profileName: profile47
    id: 47
  - profileName: profile48
    id: 48
  N6InterfaceProfile:
  - profileName: profile61
    id: 61
  - profileName: profile62
    id: 62
  - profileName: profile63
    id: 63
  - profileName: profile64
    id: 64
  - profileName: profile65
    id: 65
  - profileName: profile66
    id: 66
  - profileName: profile67
    id: 67
  - profileName: profile68
    id: 68
