apiVersion: nfdeploy.nephio.org/v1alpha1
kind: AusfDeploy
metadata:
  name: ausfdeploy-ausf1
  namespace: nephio-system
  labels:
    nephio.org/nf-deploy2: nfDeploy1
    nephio.org/nf-site-id: ausf1
    nephio.org/nf-type: ausf
spec:
  capacityProfile:
    requestedCpu: 4
    requestedMemory: 256
  nfInfo:
    vendor: casa
    version: "1.0"
