apiVersion: nfdeploy.nephio.org/v1alpha1
kind: InterfaceConfig
metadata:
  name: interfaceConfig1
spec:
  - name: google-cmg12u-MG1_RAN_1
    nfName: nfNameTest1
    interfaceGroup: interfaceGroupTest1
    id: 31
    ipAddr:
      - 192.168.250.163/28
    vlan:
      - 200
      - 201
  - name: google-cmg12c-LB1_Port1_SxN4
    nfName: nfNameTest2
    interfaceGroup: interfaceGroupTest2
    id: 41
    ipAddr:
      - 192.168.250.166/28
    vlan:
      - 300
      - 301
  - name: google-cmg12u-MG1_SGi_1
    nfName: nfNameTest3
    interfaceGroup: interfaceGroupTest3
    id: 61
    ipAddr:
      - 192.168.250.35/28
    vlan:
      - 400
      - 401
  - name: google-cmg12u-MG1_SGi_71
    nfName: nfNameTest4
    interfaceGroup: interfaceGroupTest4
    id: 71
    ipAddr:
      - 192.168.250.45/28
    vlan:
      - 500
      - 501
  - name: google-cmg12u-MG1_SGi_2
    nfName: nfNameTest5
    interfaceGroup: interfaceGroupTest5
    id: 91
    ipAddr:
      - 192.168.250.51/28
